#cloud-config
write_files:
  - path: /home/ubuntu/bin/worker-init.sh
    content: |
      #!/bin/bash
      JOIN="'sudo $(kubeadm token create --print-join-command)'"

      for IP in "$@"
      do
          echo "${IP} joining cluster"
          {
            ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/ssh_private_key.pem ubuntu@"$IP" 'bash -c' $JOIN
          } &
      done
      wait
runcmd:
  - chown -R ubuntu:ubuntu /home/ubuntu/bin
  - chmod +x /home/ubuntu/bin/worker-init.sh

  - kubeadm config images pull
  - kubeadm init --pod-network-cidr=192.168.0.0/16

  - mkdir -p /home/ubuntu/.kube
  - chown ubuntu:ubuntu /home/ubuntu/.kube
  - cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
  - chown ubuntu:ubuntu /home/ubuntu/.kube/config

  - sudo -H -u ubuntu bash -c 'kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml'

  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  # # ## Install helm
  - curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
  - sudo apt-get install apt-transport-https --yes
  - sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
  - sudo apt-get update
  - sudo apt-get install helm

  # # ## Install nginx ingress controller
  - kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.5.1/deploy/static/provider/baremetal/deploy.yaml --kubeconfig ~/.kube/config

  # Installing redis

  - sudo helm repo add bitnami https://charts.bitnami.com/bitnami
  - sudo helm install redis bitnami/redis
