### Might need to make a new PV for this and the second db.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-authdb-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.0.15 # Change
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db-pvc
spec:
  volumeName: nfs-authdb-volume
  selector:
    matchLabels:
      deployment.app: auth-db
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db-svc
spec:
  ports:
    - name: auth-db-port
      port: 5432
  selector:
    deployment.app: auth-db
## const conString = "postgres://<username>:<password>@auth-db-svc:5432/db";

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-db-config
data:
  POSTGRES_DB: db
  PGDATA: /data/authdb
  AUTHDB_HOST: postgresql://auth-db-svc:5432/db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
  labels:
    deployment.app: auth-db
spec:
  serviceName: auth-db-svc
  replicas: 1
  selector:
    matchLabels:
      deployment.app: auth-db
  template:
    metadata:
      labels:
        deployment.app: auth-db
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: auth-db-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /data
              name: pgdatavol
      volumes:
        - name: pgdatavol
          persistentVolumeClaim:
            claimName: auth-db-pvc
