apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
  # labels: #Labels
  #   deployment.app: auth-db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.0.15
    path: "/data"
