apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-authdb-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.0.15
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-db-sa
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db-svc
  labels:
    deployment.app: auth-db
spec:
  #Comment1: For troubleshooting if you need to connect to the PostgreSQL Cluster from outside the Kubernetes Cluster
  #Comment the next line `clusterIP: None`
  #Comment the next line and Uncomment the subsequent line and the to be able to
  #Uncomment the subsequent line `#type: NodePort` also uncomment the line further below `#nodePort: 30100`
  # clusterIP: None
  #type: NodePort
  ports:
    - port: 5432
      name: authdb-svc
  selector:
    deployment.app: auth-db
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db-svc
  labels:
    service.name: auth-db
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 0
  selector:
    name: pgset-replica
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgset
spec:
  selector:
    matchLabels:
      deployment.app: pgset # has to match .spec.template.metadata.labels
  serviceName: pgset
  replicas: 1
  template:
    metadata:
      labels:
        deployment.app: pgset
        name: pgset-replica
    spec:
      serviceAccount: pgset-sa
      securityContext:
        fsGroup: 26
      containers:
        - name: pgset
          image: crunchydata/crunchy-postgres:centos7-10.2-1.8.0
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: PG_PRIMARY_USER
              value: primaryuser
            - name: PGHOST
              value: /tmp
            - name: PG_MODE
              value: set
            - name: PG_PRIMARY_HOST
              value: pgset-primary
            - name: PG_PRIMARY_PORT
              value: "5432"
            - name: PG_PRIMARY_PASSWORD
              value: password
            - name: PG_USER
              value: testuser
            - name: PG_PASSWORD
              value: password
            - name: PG_DATABASE
              value: userdb
            - name: PG_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: pgdata
              mountPath: /pgdata
              readOnly: false
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgset-pvc
